title: bismite開発日記

description: >-
  マルチプラットフォーム2Dゲームエンジンbismiteの開発日記
baseurl: ""
url: ""
github_username:  kabies

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
